### PR TITLE
Update EntityDefinition.json

### PR DESCRIPTION
**Pull request by cmolitor**
Added frequency as measurement type.

### CODE REVIEW

**Comment by andig** [comment]
What's the usage? A new, fitting icon would be good to not overload the bolt?

**Comment by andig** [comment]
Icon does not work: not part of definition, wrong size. Could you also check if the icon- once it has correct size- fits the visual appearance of the other icons?

**Comment by cmolitor** [comment]
I added a new icon. Resolution: 16x16 as the others. I have no better idea for frequency symbol.

**Comment by andig** [comment]
> I added a new icon. Resolution: 16x16 as the others. I have no better idea for frequency symbol.

Looks good. Please:

- clean the commit- it has conflicts now
- move frequency to the end
- remove the pdf
- add an icon-freq class to the css (otherwise icon wont appear in table)
- run the gulp build script to recompile icons

**Comment by cmolitor** [comment]
-conflicts solved
-moved frequency to end
-pdf is removed
-added icon-freq class
-I don't know what this is and how to do it (some more information would be great)

**Comment by andig** [comment]
> Sollte der zweite Betriebsstundenzähler nicht auch die Einheit "h" bekommen?

Was hat das mit diesem PR zu tun?

**Comment by bgewehr** [comment]
Nichts. Stimmt.

**Comment by andig** [comment]
See https://github.com/volkszaehler/volkszaehler.org/pull/394

**Comment by andig** [comment]
PS  @cmolitor: whats the use case for this measurement by the way?

**Comment by cmolitor** [comment]
I am logging data from a Socomec Diris A40. One measurement is the frequency, mainly for curiosity.

**Comment by justinotherguy** [comment]
oh, that looks interesting. Have you heard of http://netzsin.us/ ?
I can't seem to find information on the accuracy of the device - do you know?

**Comment by cmolitor** [comment]
Datasheet:
https://www.socomec.com/files/live/sites/systemsite/files/SCP/6_gestion_energie/diris/diris_a40/535747b.pdf

Page 55. However, I am not sure what that means in terms of Hz.

I wasn't aware of netzsin.us. Looks interesting. 
I was only aware of http://www.netzfrequenzmessung.de

**Pull request closed without merging**
