### PR TITLE
Reduce HTTP traffic

### PR DESCRIPTION
**Pull request by andig**
- bundle flot files into single, minimized js
  - bundle jquery extensions into single, minimized js
  - reduced css sprites size

**Benefit:** less http roundtrips, less data to transfer
**Downside:** need to switch to non-minimized files again for development

### CODE REVIEW

**Comment by andig** [comment]
Looking for approval here- is the downside acceptable?

**Comment by jahir** [comment]
Is the downside still valid? You can use sourcemaps nowadays. (link from http://jquery.com/download/: http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/). I did not try it myself, though. Event then I guess we seldomly debug flot or jquery.

Anyways, +1 from me.

**Comment by jahir** [comment]
Reverted since it breaks the frontend (hopefully that'll teach me not to merge without real testing)

You reference the non-existent files javascripts/jquery/jquery-ext.min.js and javascripts/flot/flot.min.js in htdocs/frontend/index.html. Are they supposed to be auto-generated, did you forget to add them to your commit or am I missing something else?

**Comment by andig** [comment]
Sorry for that. Files were still in my folder so it didn't come up in my test. For the records: I've added one sorce fix to flot as my PR there didn't go through. Its documented of course...

**Pull request merged**
