### PR TITLE
Implement token-based access control

### PR DESCRIPTION
**Pull request by andig**
This PR provides:

  - token authentication for users using JSON web tokens
  - configurable firewall rules to adjust which networks need to authenticate or not
  - awareness of reverse proxy e.g. when using high performance middleware
  - simplified and restructured configuration template

**Warning**: login via username/password should only **ever** be enabled over secure (that is HTTPS) connections!

### CODE REVIEW

**Comment by princemichi** [comment]
Hello,
i would love to see this PR in master because of missing password authentication in VZ.
***Push***
Please add this function ASAP to the MASTER.
Thanks!
BR, Michael

**Comment by andig** [comment]
You can already use the jwt or next branch on my fork in the meantime

**Comment by ypid** [comment]
@andig You closed this PR? It also looks really interesting to me :+1:

**Comment by andig** [comment]
There was no feedback on the mailing list. If you want to use it please use my repo/ the next branch.

**Comment by ypid** [comment]
I will check it out. Thanks :+1:

**Pull request closed without merging**
