### PR TITLE
Inline JpGraph to avoid download volume

### PR DESCRIPTION
**Pull request by andig**
Cost is 4MB for inlined files vs. 40MB for the jpgraph repo dependency

### CODE REVIEW

**Comment by r00t-** [comment]
(still about https://github.com/volkszaehler/volkszaehler.org/issues/227 i guess?)

what happened to the reduced-size fork in https://github.com/volkszaehler .
i would still prefer an external repo over inlining rerely-used code.

if you have any reasons to prefer inlining, merge for all i care.

**Comment by andig** [comment]
> i would still prefer an external repo over inlining rarely-used code.

I can't remember when you've mentioned that before (and it would have been easier to know), but possible. We would loose all links to jpgraph/jpgraph though but that shouldn't hurt too much as it's dead anyway.

From 227:

> if you want my personal preference, then i'd make installing jpgraph optional and off by default.

Thinking about it this is even simpler. Why not do this:

  - make it optional (add to composer.json as suggested package)
  - have the installer ask if user wants it (default off)

Would probably also speed up our travis build process even more.

**Comment by jahir** [comment]
>Thinking about it this is even simpler. Why not do this:
> - make it optional (add to composer.json as suggested package)
> - have the installer ask if user wants it (default off)
>
>Would probably also speed up our travis build process even more.

+1!

**Comment by andig** [comment]
Closed in favor of #279

**Pull request closed without merging**
