### PR TITLE
Performance: add chaching

### PR DESCRIPTION
**Pull request by andig**
Requires APCu installed (default on raspi):

  - cache entity query results from db (entities rarely change)
  - cache expensive reading and parsing of EntityDefinition.json and PropertyDefinition.json

On my windows test machine this PR takes ~20-30% off every call to `entity.json` and reduces the same amount of time from calls to `data.json`.

**NOTE**: this should be tested/ confirmed on RasPi, combined with creating and editing entities.

### CODE REVIEW

**Comment by andig** [comment]
**Note:** with this PR, editing `EntityDefinition.json` and `PropertyDefinition.json` is only immediately effictive in dev mode or when `$config['cache']['ttl'] = 0;`

**Comment by jahir** [comment]
Do you have test cases? I see no difference to the current master. My server is an Opteron 1214HE, so nothing fancy, your Windows machine is probably much beefier.
I have currently no RPi running, so I'd need to setup one first.

Also, my groups are shown as empty. Can you confirm this?

**Comment by andig** [comment]
> Also, my groups are shown as empty. Can you confirm this?

Confirmed and investigating, thanks.

Test case is regular FE call to data.json with and without caching enabled. ~300ms difference on by Core i5 machine, speedup confirmed using XDebug/WinCacheGrind.

**Comment by andig** [comment]
@jahir Please take a loot at the test. I hate this workaround. If we don't want to use the EntityController caching we could still go with the Definition.php changes. Could you check what you prefer?

**Comment by andig** [comment]
Updated again and removed hack. Cache usage must be explicitly requested and is only user by `DataController` for performance reasons. `DataController` does not require access to child entities or properties.

**Comment by andig** [comment]
@jahir  over to you

**Comment by jahir** [comment]
Ok, but "We can’t automatically merge this pull request."
Could you resolve this, please?

**Comment by andig** [comment]
Sure. Are you happy with the current solution? Then I'd squash the commit.

**Comment by jahir** [comment]
As I wrote, I see no improvement, but as it may help small machines, I'm good with it as long as it breaks nothing. I trust you on this one :)

**Comment by andig** [comment]
@jahir did you use this test case:

> Test case is regular FE call to `data` context with and without caching enabled. ~300ms difference on by Core i5 machine, speedup confirmed using XDebug/WinCacheGrind.
> Do you have apcu installed? Do you have cache.ttl set to something like 3600?

**Comment by jahir** [comment]
A single retrieval of one week's S0 data on my server (less than average VM) running current master takes about 200ms, so I surely won't be able to save 300ms.
But ok, I wrote a test script (averages over 10 retrievals) and I see the average going down to ~110ms, so yes, there's definitely an improvement.

**Comment by jahir** [comment]
@andig After updating I noticed that new data won't go into the database. Is it just me or is this is bug in your changes?

**Comment by jahir** [comment]
sorry, had to revert to 954baea0c2 since POST was b0rked. please reopen.

**Comment by andig** [comment]
Was steht in options.js?

**Comment by jahir** [comment]
Getestet mit  $config['cache']['ttl'] = 600; aber selbst wenn das auskommentiert ist, werden POSTs einfach ignoriert.

**Comment by andig** [comment]
https://github.com/volkszaehler/volkszaehler.org/commit/954baea0c2678ca230102a5bfb60a13a87edddaa is the wrong commit for this problem. The problematic commit is https://github.com/andig/volkszaehler.org/commit/c6ca3cfa07a92ea8b16895d3854063f2ea4967d8.

I've created https://github.com/volkszaehler/volkszaehler.org/pull/228 which replaces https://github.com/volkszaehler/volkszaehler.org/pull/215.

**Pull request merged**
