### PR TITLE
Add web socket support

### PR DESCRIPTION
**Pull request by andig**
**Please don't merge**

For details see https://github.com/andig/volkszaehler.org/blob/push-sockets/misc/tools/push-server.md

### CODE REVIEW

**Comment by andig** [comment]
cc @schnello

**Comment by Sineos** [comment]
Many, many thanks for working on #428.

I merged your pull request and it works nicely. My node-red instance on 192.168.178.10 connects nicely to ws://192.168.178.8:8082/socket via the websocket node. 
Live updates in the frontend is working too.

**Comment by andig** [comment]
Thanks for the feedback and glad its working.

**Comment by Sineos** [comment]
Here is my example to get the push-server's readings into influxdb via the mqtt protocol:
https://github.com/Sineos/Push-Volkszaehler-Readings-to-Influxdb-via-MQTT

**Comment by andig** [comment]
Sounds good, so we can merge this one?

**Comment by Sineos** [comment]
Works for me since two days without any issue. Many thanks

**Pull request merged**
