### PR TITLE
Implement Symfony HTTPKernelInterface

### PR DESCRIPTION
**Pull request by andig**
This PR is a major rewrite of the basis Volkszaehler middleware request/response infrastructure. 

Instead of using PHP global request variables and outputting results directly to the browser, all input/output is channeled through the defacto-standard Symfony HTTPFoundation `Request` and `Response` components (http://symfony.com/doc/current/components/http_foundation/introduction.html).

To structure this process, input/output follows the design paradigm of Symfony HTTPKernel (http://symfony.com/doc/current/components/http_kernel/introduction.html).

The main benefit of this rewrite is the greatly improved testability of middleware functionality (plus additional tests implemented). Future uses may include stackability of Volkszaehler middleware in other applications (https://igor.io/2013/02/02/http-kernel-middlewares.html).

To keep the overhead and especially implementation complexity and learning curve of the additional libraries used low, this require does NOT use a microframework. However, porting Volkszaehler to e.g. Silex can now be done with minor additional changes.

**NOTE** Though these changes have undergone testing they cannot be considered production quality yet.

Does fix https://github.com/volkszaehler/volkszaehler.org/issues/199

### CODE REVIEW

**Comment by andig** [comment]
@jahir I realize it's a lot of changes. Could I ask you for a review? I especially like the greatly improved testability and additional test cases.

**Comment by jahir** [comment]
Sorry, a little busy right now, hope to be able to look at it in the next few days.

Obviously, it will make us depend more on Simfony. There were talks about getting rid of it, but I guess that's out of debate now.

I cannot judge if using HTTPFoundation/HTTPKernel is the right thing to do, so I have to trust you on that.
I tested your changes and they seem to run just fine.

But if you consider it not production quality, shouldn't we put it in a separate branch for now?
What is missing to be production ready?

**Comment by andig** [comment]
> Obviously, it will make us depend more on Simfony. There were talks about getting rid of it, but I guess that's out of debate now.

From what I've seen the Symfony components have become de-facto standard in many areas.

> What is missing to be production ready?

Testing, testing and testing in real life.

> But if you consider it not production quality, shouldn't we put it in a separate branch for now?

We could. However that does not attract testers by itself. If we go that way- in order to get some return- I would start pushing new features to that branch exclusively and no longer to master and would also need to start promoting that branch.

Or rather: we would first need to come up with a workable branching model.

**Comment by andig** [comment]
BTW, sophisticated branching model here: http://nvie.com/posts/a-successful-git-branching-model/ 
Likely overengineered for our purposes.

**Comment by andig** [comment]
@jahir ich finde die Idee gar nicht verkehrt. Mein Vorschlag wäre:

  - **master**: stabile Version, nur Bug Fixes
  - **development**: bleeding edge mit allen Features (dann bräuchte ich aber die Freiheit mich in dem Branch auszutoben)
  - **feature xy**: sollten normalerweise nur bei mir im "Quellrepo" existieren

Was meinst Du?

**Comment by jahir** [comment]
Hört sich gut an, aber wann und wie übernehmen wir die devel-Änderungen in den master? Und bei diesem PR würde es auch nicht helfen, wie du auch schon geschrieben hast fehlen dann die Tester. Ein devel-branch zum austoben bringt ja auch nichts, das kannst du heute auch schon in deinem fork.
Sinnvoller fände ich ein debian-ähnliches System, allerdings nur mit unstable und testing: Neue PRs in unstable ("devel"), wenn's läuft nach einger Zeit (Stunden bis Tage) mergen nach testing ("master").

**Comment by andig** [comment]
> Neue PRs in unstable ("devel"), wenn's läuft nach einger Zeit (Stunden bis Tage) mergen nach testing ("master"). 

So hatte ich das gemeint. "Wenns läuft" finden wir aber nur raus wenn es noch user gibt. Insofern muss dann ein gewisser Druck entstehen den "devel" Zweig zu nutzen. Ich fange mal damit an diesen Zweig zu eröffnen. Dann können wir mit dem Modell mal experimentieren und Erfahrungen sammeln. Kaputt geht ja nichts....

**Comment by andig** [comment]
Branch erstellt: https://github.com/volkszaehler/volkszaehler.org/tree/development

PRs für neue Features müssen künftig gegen diesen Branch erstellt werden.

**Comment by andig** [comment]
Note: Reopening PR against master as back-log

**Comment by jahir** [comment]
I just noticed that this change breaks using httpd rewrites (like we have in htdocs/.htaccess):
```
$ curl 'my.vz.host/middleware/data/b1a5c6e0-33e4-11e0-8eb1-e9d75b59e23a.csv'
{"version":"0.3","exception":{"message":"Unknown context: 'mw'","type":"Exception","code":0}}
```

handleRaw() in Router.php now uses getPathInfo() from Symfony\Component\HttpFoundation\Request, which does some obscure things (well, the usual framework "we know it better" fuck-up) instead of simply trying $_SERVER['PATH_INFO'] first (like the now removed getPathInfo() in Router.php did before).
So this is a Simfony bug, but we should work around that until they got their stuff fixed, otherwise it will break existing setups.

**Comment by andig** [comment]
What do I need to reproduce this as setup?

**Comment by jahir** [comment]
If you use the default htdocs/.htaccess file (and rewriting is not disabled in your apache config for .htaccess files), just run a request with "$server/middleware/$context..." instead of "$server/middleware.php/$context..."

**Comment by andig** [comment]
Can reproduce and will check. Btw, our htaccess doesn't work on apache 2.4

	# Deny from all
	# Allow from localhost 127.0.0.1

has to be 

	Require host 127.0.0.1

Guess we should update when Debian changes default apache?

**Comment by jahir** [comment]
FWIW, I opened a Symfony issue: https://github.com/symfony/symfony/issues/14064

Für das Require-Thema hab ich mal https://github.com/volkszaehler/volkszaehler.org/issues/280 aufgemacht. ("Require host 127.0.0.1" ist übrigens falsch, das müßte "Require host localhost" oder "Require ip 127.0.0.1" heißen, aber eigentlich willst du "Require local")

**Comment by andig** [comment]
Actually, I guess it is https://github.com/symfony/symfony/issues/13617

Could you check if rewrites are ok if your change

    $pathInfo = $request->getPathInfo();

to

    $pathInfo = $request->server->get('PATH_INFO');

**Comment by jahir** [comment]
https://github.com/symfony/symfony/issues/13617 is about getBaseUrl(), which is used by the current getPathInfo(). I don't know why they don't simply use PATH_INFO.

I already have

    $pathInfo = $_SERVER['PATH_INFO'];

as a workaround in my local code, but your suggestion works just as good (and is probably cleaner).

**Comment by andig** [comment]
> but your suggestion works just as good (and is probably cleaner).

You have to keep in mind that `Request`s are not necessarily created by apache but can also be passed in by upstream applications, e.g. our test cases or the new httpd. httpd e.g. converts an Apache request to a `React\Htttp` request and then via Symfony bridge to a `Symfony\Request`.

I wouldn't rely on super globals to be properly set, especially in the test scenario...

**Comment by jahir** [comment]
as I wrote, it was only a workaround for the b0rked symfony method, never intended to go upstream...

**Comment by andig** [comment]
@jahir: ok to commit if I add the fix for `pathInfo`? Would really love to get this in:

  - better tests
  - more tests
  - get rid of hacky test wrappers
  - htttpd
  - tests for httpd
  - less code

**Comment by jahir** [comment]
yes, I'm totally good with that. 
We can remove our pathinfo workaround later, when the symfony guys fixed their getPathInfo().

**Comment by andig** [comment]
Committing with fix applied.

**Comment by andig** [comment]
Symfony issue https://github.com/symfony/symfony/issues/13617 has been fixed.

**Pull request merged**
