### PR TITLE
composer done right

### PR DESCRIPTION
**Pull request by christian-weiss**
Fix dependency issue: (react/http) switch from development releases to stable releases. And avoid "works for me situations" for team and community by using composer good practices (lock file)

Since php-pm composer packages has changed its dependency to react/http from "dev-master" to a stable release ("^0.8") about 7 days ago there was a dependency issue introduced into volkszaehler.org project, as you can see when running "bash install.sh":

> 
> [...]
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - php-pm/php-pm dev-master requires react/http ^0.8 -> satisfiable by react/http[v0.8.0] but these conflict with your requirements or minimum-stability.
>     - php-pm/php-pm dev-master requires react/http ^0.8 -> satisfiable by react/http[v0.8.0] but these conflict with your requirements or minimum-stability.
>     - Installation request for php-pm/php-pm dev-master -> satisfiable by php-pm/php-pm[dev-master].
> 
> Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
> [...]

This pull requests fixes the dependency issue. In general it is recommended to use stable release of external dependencies. When an external package evolves bad things can happen to some team/community members due to the run "composer install" at a different point in time and when a composer.lock file is missing, even when no project code has changed. The missing composer.lock file in master branch can introduce "works for me situations". As long as the master branch is the source for "bash install.sh" you should have a composer.lock in your repo.

Another recommendation is to use a "development" branch to keep the "install.sh" working (keep the master branch stable). Using "master" branch as a release branch for stable releases is e.g. a good advice if you plan to make volkszaehler itself available as a composer package on packagist.org.

### CODE REVIEW

**Comment by christian-weiss** [comment]
@andig the last commit on master was broken: 1 of 10 travis jobs is with success.
https://travis-ci.org/volkszaehler/volkszaehler.org/builds/317302663

With my PR above, travis has 8 of 10 with success now. Hope this helps.

The last 2 failing jobs:
https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/318727871
https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/318727872
are related to your commit (https://github.com/volkszaehler/volkszaehler.org/commit/afe25de6c97a9273a4be1ab2f366f00f92212668), i guess:

**Comment by andig** [comment]
Can't remember right now but #654 should do the trick. Thanks for putting efforts into this one!

**Comment by andig** [comment]
Should be fixed via https://github.com/volkszaehler/volkszaehler.org/commit/52d860f05923af9ea08a6f95adcf83e53a55fbed, please retest.

**Comment by christian-weiss** [comment]
@andig thanks for fixing the unit tests. Now this PR passes all travis checks.
Thanks for applying the composer.json fix.

This PR remains valid and please integrate it to your code base. It contains a composer.lock file - which is important, too. https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by andig** [comment]
@christian-weiss I'm aware of the composer.lock situation. Composer.lock basically defies benefiting from semantic versioning. Past experience shows that we've not faced any problems without the versions fixed-  however composer.lock does have its drawbacks for development, especially when supporting multiple PHP version. Therefore, at this time, I do not want to commit it.

**Comment by christian-weiss** [comment]
Agree on the "supporting multiple PHP versions" thing.

**Comment by andig** [comment]
Thank you- and we really appreciate contributions, please feel free to help further with improving vz.

**Pull request closed without merging**
