### PR TITLE
update web manifest for WebAPK

### PR DESCRIPTION
**Pull request by StefanSchoof**
Update the web manifest for WebAPK installs for nicer icon on Android Homescreen
previous:
signal-2023-11-03-170935
with this change;
signal-2023-10-31-173556

- added needed properties `start_url` and `display`
- removed old and long deprecated field `density`, see https://github.com/angular/angular-cli/issues/1178
- remove unneeded escaping of `/`
- Add a `maskable` icon. I created this with https://maskable.app/ based on [icon.svg](https://github.com/volkszaehler/volkszaehler.org/blob/9ea4e362ddebe07b29371ac92bdd4973ffadb67a/misc/graphics/icon.svg)

Important: To have a WebAPK Install you need to serve the file over https and the `ico` folder need to be excluded from auth

### CODE REVIEW

**Comment by r00t-** [comment]
LGTM but can't test.

**Comment by r00t-** [comment]
> Imported: To have a WebAPK Install you need to serve the file over https and the ico folder need to be excluded from auth

do we provide this setup to users, i.e. in the dockerfile (or does the raspberry pi image have this)?

**Comment by StefanSchoof** [comment]
No, there is nothing provided. I use [traefik](https://traefik.io) with [desec](https://desec.io/) and letsencrypt and a google auth to have remote access to my volkszaehler. I share my config under https://github.com/StefanSchoof/traefik-config

I think having this in a image is not an easy task, because there are several other services you need to have configured.

**Comment by jahir** [comment]
LGTM

**Pull request merged**
