### PR TITLE
Added absolute humidity

### PR DESCRIPTION
**Pull request by SirkoVZ**
in g/m³

### CODE REVIEW

**Comment by Feilner** [comment]
@andig Why is this PR not merged? Absolute absolute humidity is a sensible extension.

**Comment by andig** [comment]
Seems there wasn‘t so much demand. Happy to add this....

**Review by bbr111 — CHANGES_REQUESTED** [review]
Looks good! Please merge

**Review by bbr111 — APPROVED** [review]
Looks ok!

**Pull request merged**
