### PR TITLE
Added universal counter to /lib/Definition/EntityDefinition.json

### PR DESCRIPTION
**Pull request by trabant-rgb**
A new universal pulse counter has been added to allow user/application specific use where the existing pulse counter do not match with regards to their unit. My use is i.e. to count the starts of my heating systems burner. The unit can be defined upon creation of the channel, or changed later on.

Within the EntityDefinition.json file, the universalcounter is located right next and in analogy to the universalsensor.

### CODE REVIEW

**Comment by trabant-rgb** [comment]
See https://www.mail-archive.com/volkszaehler-users@demo.volkszaehler.org/msg09787.html for more information.

**Comment by andig** [comment]
Könntest Du die Einrückung bitte konsistent machen?

**Comment by trabant-rgb** [comment]
Sorry, ich habe Deinen Update erst heute gesehen... kümmere mich um die Einrückung sobald ich kann!

**Comment by trabant-rgb** [comment]
Please let me know if this could be merged now as-is or if any other input is needed to make the decision.

**Pull request merged**
