### PR TITLE
Fix HTTP 400 not sent on exceptions when using JSON

### PR DESCRIPTION
**Pull request by andig**
While JSONP requires HTTP 200 in order to be interpreted by client, JSON should return HTTP 400 on exceptions.

This is already implemented in https://github.com/volkszaehler/volkszaehler.org/blob/master/lib/View/JSON.php#L119 however not working due to the response getting overwritten in https://github.com/volkszaehler/volkszaehler.org/blob/master/lib/View/JSON.php#L76.

### CODE REVIEW

**Comment by andig** [comment]
ping @jahir for 2nd opinion

**Comment by jahir** [comment]
opinion about the general concept (which I totally approve of) or your implementation? :)

**Comment by andig** [comment]
> opinion about the general concept (which I totally approve of) or your implementation? :)

More on the actual implementation. I've changed that part too often now :(

**Comment by jahir** [comment]
The patch looks quite extensive for such a small behavioral change, but if you need to work on the guts to get it done, so be it. I have not much of clue about the symfony stuff, so I have to trust you on that. The code looks ok on a quick glance, so if the tests are fine, then I'd say, ship it.

**Comment by andig** [comment]
Fix https://github.com/volkszaehler/volkszaehler.org/issues/421

**Pull request merged**
