### PR TITLE
Fix install.sh www folder creation (#821)

### PR DESCRIPTION
**Pull request by KanteTaete**

### CODE REVIEW

**Comment by andig** [comment]
The indentation looks strange on github- could you double-check?

**Comment by KanteTaete** [comment]
@andig Thanks for the comment!
The standard text editor of Linux Mint replaces tabs by blank spaces. I've fixed this - hope, I haven't missed any...

BTW: Any editor you recommend for Linux when you're not working in the terminal? For Windows it's clear for me - Notepad++ but for Linux I haven't coded much in the x system :-)

**Comment by mbehr1** [comment]
I can recommend Visual Studio Code. Available for Win, Linux, Mac. For free. Lots of good extensions (I added a few as well, check mbehr1 in marketplace :-)

**Comment by andig** [comment]
Vielen Dank. Die Empfehlung für VSCode kann ich nur unterstreichen- sei es mit Golang, Platformio oder weiteren Plugins.

**Pull request merged**
