### PR TITLE
EntityDefinition improvements

### PR DESCRIPTION
**Pull request by frankrichter**
- added "watertotal" and "heattotal" with absolute meter readings
- moved "user" to other aggregators

### CODE REVIEW

**Comment by J-A-U** [comment]
+1

**Comment by andig** [comment]
Not a big fan of yet more sebsot types for- currently- a single user. Thats why we've created the Universal type where you can soecify your own unit?

**Comment by frankrichter** [comment]
The universal type doesn't fit here: the 2 added entity types need AccumulatorInterpreter, not  SensorInterpreter. Additionally hasConsumption is missing.

**Comment by andig** [comment]
I've been wondering for a while if we should make `hasConsumption` configurable rather than hard coded?

**Comment by frankrichter** [comment]
Universal type with hasConsumption configurable would bei nice, but i'm not sure if it makes sense to have it configurable for temperature/humidity/voltage/... channels (there it makes no physical sense) or energy channels (there it's essential).

**Comment by andig** [comment]
@frankrichter to get this merged- could you move the user to its original place? I had at some point put all groups together and would like to keep it like that.

**Comment by frankrichter** [comment]
No problem to do this, but the original place is between universalsensor and filllevel - i can't see why it fits better there?

**Comment by andig** [comment]
Your placement is actually better- sorry for not checking upfront.

**Pull request merged**
