### PR TITLE
Some XHTML fixes

### PR DESCRIPTION
**Pull request by BlueAndi**

### CODE REVIEW

**Comment by andig** [comment]
Does this pr address any actual problems?

**Comment by BlueAndi** [comment]
No, it doesn't for IE, Firefox and Safary. The browser engine compensate them.
It just decrease the number of warnings regarding XHTML validatio according to the specified XHTML version in the index.html.

BTW the index.html contains the attribute sizes in the link tags. They were introduced in HTML5 IMHO, but not for XHTML. Is there a plan to jump to HTML5?

**Comment by andig** [comment]
Could you check if https://github.com/volkszaehler/volkszaehler.org/pull/467 works for you? Seems to be the simplest fix and takes care of html5, too.

**Comment by BlueAndi** [comment]
Would solve it as well, because HTML5 doesn't care about tag closing.
What maybe should be changed too:

```
<!-- HTML5 -->
<meta charset="utf-8">
<!-- HTML 4.x -->
<meta http-equiv="content-type" content="text/html; charset=utf-8">

```

And in my commit I updated the copyright year, but thats nothing important, I guess.

**Comment by andig** [comment]
> What maybe should be changed too:

Did leave it as-is as the validator doesn't complain.

**Pull request closed without merging**
