### PR TITLE
Add httpd server suggested dependency

### PR DESCRIPTION
**Pull request by andig**
Follow-up of #274 as part of separate repo. 

NOT ready to commit.

### CODE REVIEW

**Comment by andig** [comment]
This should be ready for primetime now. To install run

    composer require volkszaehler/httpd:dev-master

@jahir would appreciate retest.

**Comment by jahir** [comment]
no success:
```
# ./composer.phar require volkszaehler/httpd:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package volkszaehler/httpd could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by jahir** [comment]
no success:
```
# ./composer.phar require volkszaehler/httpd:dev-master
./composer.json has been updated
Loading composer repositories with package information                                                                                                                                 Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for volkszaehler/httpd dev-master -> satisfiable by volkszaehler/httpd[dev-master].
    - volkszaehler/httpd dev-master requires php-pm/php-pm dev-decompose -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by andig** [comment]
> volkszaehler/httpd dev-master requires php-pm/php-pm dev-decompose -> no matching package found.

Yup. Marcj has updated the repo structure to allow splitting the dependencies. I'm working with him to get this sorted (https://github.com/php-pm/php-pm/pull/41) and will ping you once more that's done.

**Comment by andig** [comment]
Fixes upstream. Should _at least_ install now.

**Comment by andig** [comment]
Retested- this is ready to commit. The remaining travis error is not relevant for mainline.

**Comment by andig** [comment]
Der verbliebene Fehler ist unkritisch: https://github.com/symfony/symfony/issues/14400

**Comment by andig** [comment]
@jahir this should finally be ready to commit. All tests are passing.

**Pull request merged**
