### PR TITLE
Show tooltip when hovering data points

### PR DESCRIPTION
**Pull request by cweiske**
This is just an idea how it could be implemented. Feel free to adjust or reject.

Example code taken and modified from
 http://www.flotcharts.org/flot/examples/interacting/index.html

Resolves: https://github.com/volkszaehler/volkszaehler.org/issues/838

2021-10-20 volkszaehler tooltip

### CODE REVIEW

**Comment by cweiske** [comment]
Shall I just close this, or is there a chance it gets merged?

**Comment by andig** [comment]
I'm not sure why this is needed when the legend already shows all values?

**Comment by cweiske** [comment]
This was requested in #838, and I thought I could help. Feel free to reject.

**Comment by jahir** [comment]
I really like the idea (and actually started to add this myself a long time ago, but it didn't work immediately, so I dumped it). Yes, you can see the value in the legend (where I added them also some time ago, IIRC), but if you have more than two or three values, it's a little cumbersome to search the right line and one has to drag his eyes away from the curve to see the value, which I think is not good for user experience. So I really appreciate the pull request.

The patch is very small and non-intrusive.
I tested the changes and it looks good to me. You have to move the mouse near the actual data points (no interpolated values), but this is default behaviour of flot I think, so that's ok ("good enough").

@andig If you are not strongly opposed, I would merge it.

**Comment by andig** [comment]
Dann rein damit!

**Pull request merged**
